name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - master  # Trigger CI/CD when code is pushed to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETKEY }}
          region: ap-southeast-3

      - name: Build and push Docker image
        run: |
          docker build -t swr.ap-southeast-3.myhuaweicloud.com/anthonyorg/gitapp:${{ github.sha }} .
          docker push swr.ap-southeast-3.myhuaweicloud.com/anthonyorg/gitapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Server Shell/login to ECS on HUAWEI
        uses: tzzs/server-shell@v3
        with:
          # server private key
          PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          # server login username
          USERNAME: ${{secrets.SSH_USER}}
          # server ip
          IP: ${{secrets.SSH_HOST}}
          # The port to connect to the server ssh
          PORT: 22 # optional, default is 22
          # shell to execute on server

          # after manually installing docker on server
      - name: login to SWR, PULL and RUN image
